language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - pypy
  - pypy3
  - nightly

jobs:
  allow_failures:
    - python: nightly
  include:
    - python: pypy
      env: CRYPTOGRAPHY_ALLOW_OPENSSL_102=true

sudo: false

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - make lint
  - make test
  - make coverage

after_success:
  coveralls
