language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
  - pypy3
  - nightly

allow_failures:
  - python: nightly

sudo: false

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - make lint
  - make test
  - make coverage

after_success:
  coveralls
